# Generated by Django 4.2.4 on 2023-08-05 00:01

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClockAngle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hours",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(24),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(59),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                ("angle", models.PositiveIntegerField()),
            ],
        ),
    ]
